apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: l6azvjrvr-python
  janus-idp.io/tekton: l6azvjrvr-python
  backstage.io/kubernetes-id: l6azvjrvr-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: l6azvjrvr-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
